name: Aliyun Signin

on: 
  schedule: 
    - cron: '25 16 * * *'
  workflow_dispatch: 
jobs: 
  signin: 
    name: Aliyun Signin
    runs-on: ubuntu-latest
    steps: 
      - uses: ImYrS/aliyun-auto-signin@main
        with:
          REFRESH_TOKENS: ${{ secrets.REFRESH_TOKENS }}
          GP_TOKEN: ${{ secrets.GP_TOKEN}}
          PUSH_TYPES: 'SERVERCHAN'
          SERVERCHAN_SEND_KEY: ${{ secrets.SERVERCHAN_SEND_KEY }}
